#!/usr/bin/bash

export ISUPER_USER=outrowed
export IHOSTNAME=archie

export ITIMEZONE=Asia/Singapore
ILOCALE_GEN_LIST=(
    en_US.UTF-8
    en_GB.UTF-8
    en_IE.UTF-8
    en_DK.UTF-8
    ja_JP.UTF-8
    ja_JP.EUC-JP
    ko_KR.UTF-8
    zh_CN.UTF-8
    zh_TW.UTF-8
    zh_HK.UTF-8
    zh_SG.UTF-8
)
ILOCALE_CONF=(
    "LANG=en_US.UTF-8"
    "LANGUAGE=en_GB:en:C"
    "LC_TIME=en_DK.UTF-8"
    "LC_MEASUREMENT=en_GB.UTF-8"
)    
export IKEYMAP=us
export INTP="0.arch.pool.ntp.org 1.arch.pool.ntp.org"
export INTP_FALLBACK="0.pool.ntp.org 1.pool.ntp.org"

export IROOT_PARTITION_LABEL=arch-linux-root
export IHOME_PARTITION_LABEL=arch-linux-home
# Only ext4 is supported by the current formatter; keep this as ext4.
export IROOT_PARTITION_FSTYPE=ext4
export IHOME_PARTITION_FSTYPE=ext4

export IREFLECTOR_COUNTRY="Singapore"
export IREFLECTOR_LATEST=10

# Swap configuration: zram or swapfile
export ISWAP_TYPE=zram+swapfile

# EFI System Partition location
# IEFI_DEVICE and IEFI_PARTITION_INDEX are derived automatically from IEFI_PARTITION.
export IEFI_PARTITION=/dev/nvme0n1p1
# IEFI_LINUNX_DIRNAME is the directory stored in the ESP, must be safe non-space characters (regex: /[a-zA-Z-_]+/)
export IEFI_LINUX_DIRNAME=arch-linux

export IBOOTLOADER=systemd-boot

export ISYSTEMD_BOOT_ARCH_LABEL="Arch Linux"
export ISYSTEMD_BOOT_EFI_LABEL="Arch Linux Boot Manager"

export IUKI_LABEL="Arch Linux"
export IUKI_EXEC=arch.efi

# Kernel command line appended after root=UUID=... in install.sh
export IKERNEL_CMDLINE="rw nvidia_drm.modeset=1 i915.enable_guc=2 quiet splash rd.systemd.show_status=auto systemd.gpt_auto=0"

# Optional zswap tuning appended only when zram is enabled
export IKERNEL_ZSWAP_CMDLINE="zswap.enabled=1 zswap.compressor=zstd zswap.zpool=z3fold zswap.max_pool_percent=20"

# Which initramfs layout to use: busybox or systemd
export IINITRAMFS_TYPE=systemd

# By default, the installation does not set resume= and resume_offset= for hibernation in systemd-based init
# This is because systemd uses HibernationLocation EFI variable (automatically generated by systemd-hibernate.service)
# ... but this may not work on dual boot linux system
export IEXPLICIT_RESUME_ARGS=false

# Path for visudo editor
export IVISUDO_EDITOR=/usr/bin/nano

# Install pylolcat for funzies
export IPYLOLCAT=true
