[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "march"
version = "0.1.0"
authors = [
    { name = "Outrowed", email = "outrowed@gmail.com" }
]
description = "Opinionated Arch Linux installer."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.12"
keywords = ["arch-linux", "installer", "bootstrap", "system-setup"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Topic :: System :: Installation/Setup"
]
dependencies = [
    "tomli>=2.4.0",
    "tomli-w>=1.0.0",
    "pydantic>=2.0.0"
]

[tool.setuptools]
py-modules = ["march"]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["core*", "plugins*"]
namespaces = true

[tool.setuptools.package-data]
"plugins" = ["plugin-loader.toml"]

[tool.setuptools.data-files]
"share/march/conf" = ["conf/*.toml"]
