
default_hostname = "archie"

[branding]
name = "Arch Linux"
pretty_name = "Arch Linux"
safe_name = "arch-linux"

boot_entry_name = "Arch Linux"
boot_manager_name = "Arch Linux Boot Manager"

[users]
wheel_user = "outrowed"

user_names = []
default_password = "a_default_password123"

[localization]
keymap = "us"
locale_gen = [
    "en_US.UTF-8",
    "en_GB.UTF-8",
    "en_IE.UTF-8",
    "en_DK.UTF-8",
    "ja_JP.UTF-8",
    "ja_JP.EUC-JP",
    "ko_KR.UTF-8",
    "zh_CN.UTF-8",
    "zh_TW.UTF-8",
    "zh_HK.UTF-8",
    "zh_SG.UTF-8"
]
locale_conf = {
    LANG = "en_US.UTF-8",
    LANGUAGE = "en_GB:en:C",
    LC_TIME = "en_DK.UTF-8",
    LC_MEASUREMENT = "en_GB.UTF-8"
}

[timedate]
timezone = "Asia/Singapore"

[timedate.ntp]
main = "0.arch.pool.ntp.org 1.arch.pool.ntp.org"
fallback = "0.pool.ntp.org 1.pool.ntp.org"

[network]
# networkmanager | systemd-networkd (unsupported yet)
backend = "networkmanager"
# wpa_supplicant | iwd
wifi_backend = "wpa_supplicant"

[network.dns]
# networkmanager | systemd-resolved | dnsmaq
backend = "systemd-resolved"
main = "1.1.1.1#cloudflare-dns.com 1.0.0.1#cloudflare-dns.com"
fallback = "9.9.9.9#dns.quad9.net"
over_tls = true
sec = false

[partition]
reformat = false
create_if_not_exist = true
# partition to find with empty space, if nvme is not empty, then go to sd
partition_order = [
    "/dev/nvme",
    "/dev/sd",
]

[partition.target]
esp = {
    query = "LABEL=ESP",
    label = "ESP",
    size = "1GB",
    fs = "esp",
    reformat = false,
}
root = {
    query = "LABEL=arch-linux-root",
    label = "arch-linux-root",
    fit_size = "60%",
    fs = "ext4",
}
home = {
    query = "LABEL=arch-linux-home",
    label = "arch-linux-home",
    fit_size = "40%",
    fs = "ext4",
}

[pacman]
color = true
parallel = 6
repository_list = [
    "core",
    "cachyos-v3",
    "cachyos",
    "chaotic-aur"
]
aur = "paru"
reflector_options = """
--country Singapore \
--latest 10 \
--protocol https \
--sort rate \
--age 12 \
"""
reflector_save = "/etc/pacman.d/"

[mkinitcpio]
# Which initramfs layout to use: busybox | systemd
initramfs_type = "systemd"
hooks_exclude = []
module_templates = []

[swap]
enable = true
zswap = true
size = "ram * 1.5"
# By default, the installation does not set resume= and resume_offset= for hibernation in systemd-based init
# This is because systemd uses HibernationLocation EFI variable (automatically generated by systemd-hibernate.service)
# ... but this may not work on dual boot linux system
explicit_resume_kernel_args = false

[swap.zram]
enable = true
size = "min(ram / 2, 4096)"

[bootloader]
kernel_options =  """
rw \
nvidia_drm.modeset=1 \
i915.enable_guc=2 \
rd.systemd.show_status=auto \
systemd.gpt_auto=0 \
quiet splash \
"""

[bootloader.systemd-boot]
enable = true
timeout = 5

[bootloader.uki]
enable = false
