
default_hostname = "archie"

[branding]
name = "Arch Linux"
pretty_name = "Arch Linux"
safe_name = "arch-linux"

bootloader_name = "Arch Linux"
boot_manager_name = "Arch Linux Boot Manager"

# override names/identifiers set from this config
override_config = true

[users]
wheel_user = "outrowed"

user_names = []
default_password = "a_default_password123"

passwords_directory = "{PROGRAM}/passwords"

[localization]
timezone = "Asia/Singapore"
keymap = "us"
locale_gen = [
    "en_US.UTF-8",
    "en_GB.UTF-8",
    "en_IE.UTF-8",
    "en_DK.UTF-8",
    "ja_JP.UTF-8",
    "ja_JP.EUC-JP",
    "ko_KR.UTF-8",
    "zh_CN.UTF-8",
    "zh_TW.UTF-8",
    "zh_HK.UTF-8",
    "zh_SG.UTF-8"
]

# locale.conf
[localization.locale_conf]
LANG = "en_US.UTF-8"
LANGUAGE = "en_GB:en:C"
LC_TIME = "en_DK.UTF-8"
LC_MEASUREMENT = "en_GB.UTF-8"

[ntp]
main = "0.arch.pool.ntp.org 1.arch.pool.ntp.org"
fallback = "0.pool.ntp.org 1.pool.ntp.org"

[systemd-resolved]
dns = "1.1.1.1#cloudflare-dns.com 1.0.0.1#cloudflare-dns.com"
dns_fallback = "9.9.9.9#dns.quad9.net"
dns_over_tls = true
dns_sec = false

[partitions]
# Only ext4 is supported
root.query = "LABEL=arch-linux-root"
root.fs = "ext4"
home.query = "LABEL=arch-linux-home"
home.fs = "ext4"

[btrfs]
subvolumes = []

[pacman]
color = true
parallel = 6

[pacman.reflector]
country = "Singapore"
latest = 10

[pacman.aur]
# AUR helper to use for AUR packages: paru or yay.
helper = "paru"

[mkinitcpio]
# Which initramfs layout to use: busybox or systemd
initramfs_type = "systemd"

[swap]
enable = true
zswap = true
size = "ram * 1.5"
# By default, the installation does not set resume= and resume_offset= for hibernation in systemd-based init
# This is because systemd uses HibernationLocation EFI variable (automatically generated by systemd-hibernate.service)
# ... but this may not work on dual boot linux system
explicit_resume_kernel_args = false

[swap.zram]
enable = true
size = "min(ram / 2, 4096)"

[bootloader]
# EFI System Partition location
# IEFI_DEVICE and IEFI_PARTITION_INDEX are derived automatically from IEFI_PARTITION.
esp = "DEV=/dev/nvme0n1p1"
# IEFI_LINUNX_DIRNAME is the directory stored in the ESP, must be safe non-space characters (regex: /[a-zA-Z-_]+/)
boot_dirname = "arch-linux"
# Kernel command line appended after root=UUID=... in install.sh
kernel_cmdline = "rw nvidia_drm.modeset=1 i915.enable_guc=2 quiet splash rd.systemd.show_status=auto systemd.gpt_auto=0"

[bootloader.systemd-boot]
enable = true
timeout = 5
os_label = "Arch Linux"
systemd_boot_efi_label = "Arch Linux Boot Manager"

[bootloader.uki]
enable = false
efi_label = "Arch Linux"
efi_exec = "arch.efi"
