
## Package rules
# 'include-' -- explicitly include, overriding previous rules
# 'exclude-' -- exclude these package groups
# 'spread' -- include packages from other rules
# ---
# intended to be mix-and-match with '+' operator, which has the same behavior as spread
# e.g., generic + kde + nvidia-580xx

[generic-pacstrap]
include-pacstrap = [
    'base',
    'hardware',
    'partition',
    'fs',
    'admin',
    'archive',
    'devel',
    'pacman',
    'zsh',
    'bash',
    'network',
    'wireless',
    'bluetooth',
    'audio-utils',
    'audio',
    'graphics',
]

[generic-pacman]
include-pacman = [
    'graphics',
    'admin',
    'packman',
    'power',
    'generic-de',
    'audio',
    'devel',
    'utils',
    'network',
    'localization',
    'fonts',
    'fun'
]

[generic-aur]
include-aur = [
    'packman',
    'apps',
    'cli',
    'vlc-plugins',
    'virt',
    'print',
    'usbiso',
    'nvidia-580xx',
]

[generic]
spread = [
    'generic-pacstrap',
    'generic-pacman',
    'generic-aur'
]

## Extraneous
# Include extraneous packages that are harmless for the sake of making it work out-of-the-box on other system

[extraneous]
include-all = [
    'amd',
    'nvidia',
    'intel'
]

## DE

[kde]
include-all = [
    'plasma'
]

[gnome]
include-all = [
    'gnome'
]

## Graphics

[nvidia]
include-all = [
    'nvidia',
    'cuda',
]

[nvidia-580xx]
include-all = [
    'nvidia-580xx',
    'cuda'
]

## Full
# All the packages to make a working system

[kde-full]
spread = [
    'generic',
    'extraneous',
    'kde',
]

[gnome-full]
spread = [
    'generic',
    'extraneous',
    'gnome',
]

## Misc.

[no-fun]
exclude-all = [
    'fun'
]