#!/usr/bin/bash

## Pacstrap packages
# essential packages for 'comfortable but minimal" base Arch Linux installation
# -- that may be used for rescue or recovery mode
# anything that would make sense for DE is not included here, instead in later IPACMAN_PACKAGES, IAUR_PACKAGES, or ILATE_PACKAGES
# minimize the download/installation time
[pacstrap]
base = [
    ## System + microcode
    'base',
    'linux',
    'linux-firmware',
    'intel-ucode',
    'amd-ucode',
]
base-extra = [
    # Extra
    'base-devel',
    'linux-headers',
    'zram-generator',
    'plymouth',  # boot startup
]
partition = [
    # Partition
    'parted',
    'gptfdisk',
    # EFI
    'efibootmgr',
    'efivar',
]
fs = [
    'btrfs-progs',
    'ntfs-3g',
    'dosfstools',
    'e2fsprogs',
]
admin = [
    'sudo',
    'openssh',
    'openssl',
    'fuse3',
    'sshfs',
    # System info
    'btop',  # alternative to htop
    'fwupd',  # firmware updates
    'fastfetch',
    # Remote downloader
    'git',
    'curl',
    'wget',
    'rsync',
    # Text editor
    'nano',
    'vim',
    # Text util
    'man-db',
    'man-pages',
    'less',
    'dos2unix',  # convert CRLF to LF
    # Archival
    'gzip',
    'xz',
    'zip',
    'unzip',
    '7zip',
    # FS listing / finder
    'tree',
    'plocate',  # 'everything" file finder in linux
]
devel = [
    'python',
    'shellcheck',
    'gcc',
    'make',
    'cmake',
    'pkgconf',
    'git-lfs',
    'jq',
    'go',
]
zsh = [
    'zsh',
    'zsh-completions',
    'zsh-syntax-highlighting',
    'zsh-autosuggestions',
    'grml-zsh-config',  # ArchISO Zsh Config per https://wiki.archlinux.org/title/Zsh#Sample_.zshrc_files
]
bash = [
    'bash',
    'bash-completion',
    'bash-language-server',
]
network = [
    # Core
    'iptables-nft',
    'systemd-resolvconf',
    'networkmanager',
    'ufw',  # firewall
    # Utils
    'inetutils',
    'openbsd-netcat',
    'nmap',
    'speedtest-cli',
    # Wireless
    'iwd',
    'wireless_tools',
    'wpa_supplicant',
    # Bluetooth
    'bluez',  # bluetooth support
    'bluez-utils',
    'bluez-obex',
    # Extra
    'wireguard-tools',
]
pacman = [
    ## Pacman extra
    'pacman-contrib',
    'reflector',
    'arch-audit',
]
pipewire = [
    # required to avoid conflict with jack2
    'pipewire',
    'wireplumber',
    'pipewire-jack',
    'pipewire-pulse',
    'pipewire-alsa',
]
audio-utils = [
    ## Multimedia
    'ffmpeg',
]
audio = [
    ## Audio firmware
    'sof-firmware',
    'alsa-firmware',
]
graphics = [
    ## Generic GPU
    'mesa',
]
nvidia = [
    'nvidia-open-dkms',
    'nvidia-utils',
    'nvidia-settings',
]

## Pacman packages
# packages installed after the base system installation
# usually this is where DE and graphical related things are installed
[pacman]
graphics = [
    'vulkan-icd-loader',
    'vulkan-swrast',  # Vulkan Software Rasterizer (CPU)
    'vulkan-mesa-implicit-layers',
    # ex: vulkan-mesa-device-select -- conflict with vulkan-mesa-implicit-layers
]
nvidia = [
    'nvidia-prime'
    # ex: cuda -- added in ILATE_PACKAGES
]
intel = [
    'intel-media-driver',
    'vulkan-intel',
]
amd = [
    'libva-mesa-driver',
    'vulkan-radeon',
]
admin = [
    'gparted',
    'smartmontools',
    'nvtop',
    'iotop',
    'vulkan-tools',
    # ex: timeshift
]
packman = [
    'octopi',
    'flatpak',  # mostly user-space GUI-based applications
]
generic-de = [
    'wl-clipboard',
    'xdg-utils',
    'trash-cli',
    'iio-sensor-proxy',
    # Extra
    'bolt',
    'power-profiles-daemon',
    'network-manager-applet',
    'arch-audit-gtk',
]
plasma = [
    # Core
    'sddm',
    'plasma-meta',
    'xorg-xwayland',
    # Theme
    'breeze',
    # Extra
    'kde-accessibility',
    'kde-system',
    'kde-utilities',
    'kde-graphics',
    # ex: kde-network
    # ex: kde-office
    # ex: kde-multimedia
    # KCM
    'sddm-kcm',
    'plymouth-kcm',
    # Remote
    'krdc',
    # Plugin + integration
    'kdenetwork-filesharing',
    'plasma-thunderbolt',
    'plasma-keyboard',  # plasma virtual keyboard
    # KIO
    'kio-admin',
    'kio-extras',
    'kio-gdrive',
    'kio-zeroconf',
]
gnome = [
    ## Core
    'gdm',
    'gnome',
    'gnome-circle',
    # Extra
    'gnome-extra',
    'gnome-tweaks',
    ## Extensions
    'gnome-shell-extensions',
    'gnome-browser-connector',

]
audio = [
    'phonon-qt6-vlc',
    'alsa-utils',
    'gst-plugin-pipewire',
    'pavucontrol',
    # Audio player
    'mpv',
    'vlc',
    # Audio utils
    'ffmpegthumbs',
]
network-extra = [
    'avahi',  # Network discovery (mDNS/Bonjour)
    'nss-mdns',  # Hostname resolution for .local domains
    'zerotier-one',
]
localization = [
    'hunspell',
    'hyphen',
]
devel = [
    # AUR VSCode
    'code',
    'code-features',
    'code-marketplace',
    # NodeJS
    'nodejs',
    'npm',
    'pnpm',
    # misc
    'jdk-openjdk',
    'mypy',
]
utils = [
    'ark',          # archive manager
    'audiorelay',   # Android/PC mic and audio mirroring
    'scrcpy',       # Android/PC screen mirroring
    'gif2png',      # gif to png converter
    'kgpg',         # KDE gpg manager
    'syncthing',    # syncthing
    'yt-dlp',       # youtube download
    'bat',          # cat clone
]
extra = [
    'rbw',
    'cryptomator-cli'
]
fonts = [
    'ttf-dejavu',
    'ttf-liberation',
    'ttf-roboto',
    'gnu-free-fonts',
    'ttf-ms-fonts',
    'noto-fonts',
    'noto-fonts-cjk',
    # Emoji / custom icon
    'noto-fonts-emoji',
    'nerd-fonts',
    'otf-font-awesome',
    # Mono
    'ttf-jetbrains-mono',
    'ttf-cascadia-code',
    # Bitmap
    'bdf-unifont',
]
virt = [
    'qemu-desktop', # QEMU setup for desktop environment
    'virt-manager', # GUI front end for virtualization
    'libvirt',      # virtualizatin API
    'edk2-ovmf',    # UEFI firmware for virtual machines
    'virt-viewer',  # graphical display required by virt-manager
    # Virt utils
    'dnsmasq',  # DNS + DHCP server -- host uses systemd-resolved instead
    'dmidecode',  # system hardware report via SMBIOS/DMI standard
]
print = [
    'cups',                         # The core printing system
    'cups-pdf',                     # Print to PDF support
    'gutenprint',                   # High-quality drivers for Canon, Epson, etc.
    'foomatic-db-gutenprint-ppds',  # PPD files for Gutenprint
    'hplip',                        # Drivers for HP printers
]
fun = [
    'c-lolcat',
    'yumenikki-en',
    'classicube',
    'supertuxkart',
    'kblocks',
]

## AUR packages
# run with no password sudo
[aur]
cuda = [
    'cuda',             # big boi NVIDIA driver
]
packman = [
    'topgrade',     # upgrades everything
    'paru',         # AUR helper
    'needrestart',  # automatically restart daemon after library update
]
gnome = [
    'gnome-shell-extension-sound-output-device-chooser',
]
apps = [
    'helium-browser-bin',   # ungoogled-chromium-based browser with convenient features
    'chromium-widevine',    # play DRM content on chromium-based browser (like helium). needs linking (see install-helium-widevine.sh)
    'pwvucontrol',          # native pavucontrol for PipeWire
    'elecwhat-bin',         # electron whatsapp client
]
extra = [
    'maliit-keyboard',  # maliit generic virtual keyboard
    'sunshine',         # remote server
    # ex: timeshift-systemd-timer
]
usbiso = [
    'ventoy',   # ventoy bootloader
    'archiso',  # archiso creation
]
nvidia-580xx = [
    'nvidia-580xx-dkms',
    'nvidia-580xx-utils',
    'nvidia-580xx-settings',
    'lib32-nvidia-580xx-utils',
]