## Flatpak system-wide packages
[flatpak-system]
theme = [
    "org.gtk.Gtk3theme.Breeze",
]

tools = [
    "io.github.mfat.sshpilot",
]

file-tools = [
    # File tools
    "io.github.cboxdoerfer.FSearch",
    "io.gitlab.adhami3310.Converter",
]

camera = [
    "org.kde.kamoso",
    "io.github.webcamoid.Webcamoid",
]

flatpak-tools = [
    "com.github.tchx84.Flatseal",
    "io.github.flattool.Warehouse",
]

lan-remote = [
    "org.localsend.localsend_app",
    "com.moonlight_stream.Moonlight", # sunshine
]

devel = [
    "com.gitbutler.gitbutler",
    "io.dbeaver.DBeaverCommunity",
    "org.kde.kdiff3",
    "org.kde.kompare",
    "org.octave.Octave",
]

gaming-wine = [
    # front-ends
    "com.valvesoftware.Steam",
    "com.usebottles.bottles",
    "net.lutris.Lutris",
    "net.davidotek.pupgui2",
    # compat
    "com.github.Matoking.protontricks",
    "com.vysp3r.ProtonPlus",
]

gaming-etc = [
    "org.prismlauncher.PrismLauncher",
    "org.vinegarhq.Sober",
]

office = [
    "org.onlyoffice.desktopeditors",
    "org.kde.ghostwriter",
    "org.kde.okular",
]

internet-social = [
    "dev.vencord.Vesktop", # better discord
    "org.kde.konversation",
    "org.kde.neochat",
]

internet = [
    "one.ablaze.floorp",
    # "org.mozilla.firefox", # replaced with one.ablaze.floorp
    "org.mozilla.Thunderbird",
    "es.danirod.Cartero",
    # "io.github.ungoogled_software.ungoogled_chromium", # helium-browser-bin in IAUR_PACKAGES
    "org.qbittorrent.qBittorrent",
    "org.kde.kget",
    "org.kde.alligator",
]

video = [
    "com.obsproject.Studio",
]

creative-graphics = [
    "org.gimp.GIMP",
    "org.kde.krita",
    "org.kde.kdenlive",
    "org.blender.Blender",
    "org.inkscape.Inkscape",
    "org.kde.digikam",
]

miscellaneous = [
    "info.febvre.Komikku",
    "org.godotengine.Godot",
    "com.bitwarden.desktop",
]

## Flatpak main user packages
[flatpak-user]
apps = [
    "com.spotify.Client",
    # "dev.diegovsky.Riff", # spotify backend, requires spotify premium
    # "com.vscodium.codium", # AUR code code-features code-marketplace
]

multimedia = [
    "com.github.wwmm.easyeffects",
    "org.tenacityaudio.Tenacity",
    "com.github.marinm.songrec",
    "no.mifi.losslesscut",
]