
## Pacstrap packages
# essential packages for 'comfortable but minimal" base Arch Linux installation
# -- that may be used for rescue or recovery mode
# anything that would make sense for DE is not included here, instead in later IPACMAN_PACKAGES, IAUR_PACKAGES, or ILATE_PACKAGES
# minimize the download/installation time
[pacstrap]
base = [
    # System + microcode
    'base',
    'linux',
    # Extra
    'base-devel',
    'linux-headers',
    'zram-generator',
    'plymouth',  # boot startup
]
hardware = [
    'linux-firmware',   # linux firmware
    'sof-firmware',     # Sound Open firmware
    'intel-ucode',      # intel CPU ucode
    'amd-ucode',        # amd CPU ucode
    # utils
    'fwupd',            # firmware updates
    'dmidecode',        # system hardware report via SMBIOS/DMI standard
    'dmraid',
    'hdparm',
    'hwdetect',
    'lsscsi',
    'mtools',
    'sg3_utils',
]
partition = [
    # Partition
    'parted',
    'gptfdisk',
    'fsarchiver',   # compress/restore filesystem partition
    # EFI
    'efibootmgr',
    'efivar',
]
fs = [
    # Filesystem
    'btrfs-progs',
    'ntfs-3g',
    'dosfstools',
    'e2fsprogs',
]
admin = [
    # System admin
    'sudo',
    'openssh',
    'openssl',
    'fuse3',
    'sshfs',
    # System info
    'btop',         # alternative to htop
    'fastfetch',    # check your system
    # Text editor
    'nano',
    'nano-syntax-highlighting',
    'vim',
    # Text utils
    'man-db',
    'man-pages',
    'less',
    'meld',      # file and directory comparison
    'dos2unix',  # convert CRLF to LF
    # Remote downloader
    'git',
    'git-lfs',
    'curl',
    'wget',
    'rsync',
    # FS listing / finder
    'tree',
    'plocate',  # 'everything" file finder in linux
]
archive = [
    # File archive utils
    'gzip',
    'xz',
    'zip',
    'unzip',
    '7zip',
]
devel = [
    'python',
    'shellcheck',
    'gcc',
    'make',
    'cmake',
    'pkgconf',
    'jq',
    'go',
]
pacman = [
    # Pacman utils
    'pacman-contrib',   # extra pacman utils
    'reflector',        # Arch Linux official repo mirror
    'pkgfile',          # pkgfile for AUR
    'rebuild-detector', # detect package rebuild
    'arch-audit',       # audit arch packages
]
zsh = [
    'zsh',
    'zsh-completions',
    'zsh-syntax-highlighting',
    'zsh-autosuggestions',
    'grml-zsh-config',  # ArchISO Zsh Config per https://wiki.archlinux.org/title/Zsh#Sample_.zshrc_files
]
bash = [
    'bash',
    'bash-completion',
    'bash-language-server',
]
network = [
    # Core
    'iptables-nft',
    'systemd-resolvconf',
    'networkmanager',
    'modemmanager',
    'ufw',  # firewall
    # Utils
    'inetutils',
    'openbsd-netcat',
    'nmap',
    'speedtest-cli',
    # VPN extra
    'wireguard-tools',
]
wireless = [
    # Wireless
    'iwd',
    'wireless_tools',
    'wpa_supplicant',
]
bluetooth = [
    # Bluetooth
    'bluez',            # bluetooth support
    'bluez-hid2hci',
    'bluez-libs',
    'bluez-utils',
    'bluez-obex',       # bluetooth file transfer
]
audio-utils = [
    # Multimedia
    'ffmpeg',
]
audio = [
    # Alsa
    'alsa-firmware',
    'alsa-utils',
    'alsa-plugins',
    # Pipewire
    'pipewire',
    'wireplumber',
    'pipewire-jack',
    'pipewire-pulse',
    'pipewire-alsa',
]
graphics = [
    # Generic graphics
    'mesa',
]
nvidia = [
    'nvidia-open-dkms',
    'nvidia-utils',
    'nvidia-settings',
]

## Pacman packages
# packages installed after the base system installation
# usually this is where DE and graphical related things are installed
[pacman]
graphics = [
    'vulkan-icd-loader',
    'vulkan-swrast',  # Vulkan Software Rasterizer (CPU)
    'vulkan-mesa-implicit-layers',
    # ex: vulkan-mesa-device-select -- conflict with vulkan-mesa-implicit-layers
]
nvidia = [
    'nvidia-prime'
]
intel = [
    'intel-media-driver',
    'vulkan-intel',
]
amd = [
    'libva-mesa-driver',
    'vulkan-radeon',
]
admin = [
    'gparted',
    'smartmontools',
    'nvtop',
    'iotop',
    'vulkan-tools',
    # ex: timeshift
]
packman = [
    'octopi',
    'flatpak',  # mostly user-space GUI-based applications
]
power = [
    # Power management
    'power-profiles-daemon',    # Powersaver/Balanced/Performance power profiles
    'cpupower',
    'upower',
]
generic-de = [
    'wl-clipboard',
    'xdg-utils',
    'trash-cli',
    'iio-sensor-proxy',
    # Extra
    'bolt',
    'network-manager-applet',
    'arch-audit-gtk',
]
plasma = [
    # Core
    'sddm',
    'plasma-meta',
    'xorg-xwayland',
    # Theme
    'breeze',
    # Apps
    'kde-accessibility',
    'kde-system',
    'kde-utilities',
    'kde-graphics',
    'krdc',                 # Remote desktop client
    # ex: kde-network
    # ex: kde-office
    # ex: kde-multimedia
    # KCM
    'sddm-kcm',
    'plymouth-kcm',
    'flatpak-kcm',
    # Plugin + integration
    'kdenetwork-filesharing',
    'plasma-thunderbolt',
    'plasma-keyboard',  # plasma virtual keyboard
    # KIO
    'kio-admin',
    'kio-extras',
    'kio-gdrive',
    'kio-zeroconf',
]
gnome = [
    ## Core
    'gdm',
    'gnome',
    'gnome-circle',
    # Extra
    'gnome-extra',
    'gnome-tweaks',
    ## Extensions
    'gnome-shell-extensions',
    'gnome-browser-connector',

]
audio = [
    'phonon-qt6-vlc',
    'gst-plugin-pipewire',
    'pavucontrol',
    # Audio player
    'mpv',
    'vlc',
    # Audio utils
    'ffmpegthumbs',
]
devel = [
    # AUR VSCode
    'code',
    'code-features',
    'code-marketplace',
    # NodeJS
    'nodejs',
    'npm',
    'pnpm',
    # misc
    'jdk-openjdk',
    'mypy',
]
utils = [
    'ark',          # archive manager
    'scrcpy',       # Android/PC screen mirroring
    'gif2png',      # gif to png converter
    'kgpg',         # KDE gpg manager
    'syncthing',    # syncthing
    'yt-dlp',       # youtube download
    'bat',          # cat clone
]
network = [
    # Extra network backends and utils
    'systemd-netword', # NetworkManager alternative
    'iwd',             # wireless connection alternative
    'dnsmasq',         # DNS + DHCP server; this is used for libvirt, the host uses systemd-resolved instead
    'stubby',          # DNS privacy stub resolver for dnsmasq
    'nss-mdns',        # Hostname resolution for .local domains
    'avahi',           # Network discovery (mDNS/Bonjour)
    'impala',          # iwd TUI
]
localization = [
    'hunspell',
    'hyphen',
]
fonts = [
    'ttf-dejavu',
    'ttf-liberation',
    'ttf-roboto',
    'gnu-free-fonts',
    'ttf-ms-fonts',
    'noto-fonts',
    'noto-fonts-cjk',
    # Emoji / custom icon
    'noto-fonts-emoji',
    'nerd-fonts',
    'otf-font-awesome',
    # Mono
    'ttf-jetbrains-mono',
    'ttf-cascadia-code',
    # Bitmap
    'bdf-unifont',
]
fun = [
    'c-lolcat',
    'yumenikki-en',
    'classicube',
    'supertuxkart',
    'kblocks',
]

## AUR / Pacman packages
# Installed very late after the base system and pacman packages
[aur]
cuda = [
    'cuda',             # big boi NVIDIA driver
]
packman = [
    'topgrade',     # upgrades everything
    'paru',         # AUR helper
    'needrestart',  # automatically restart daemon after library update
]
apps = [
    'helium-browser-bin',   # ungoogled-chromium-based browser with convenient features
    'chromium-widevine',    # play DRM content on chromium-based browser (like helium). needs linking (see install-helium-widevine.sh)
    'pwvucontrol',          # native pavucontrol for PipeWire
    'elecwhat-bin',         # electron whatsapp client
]
cli = [
    'audiorelay',       # Android/PC mic and audio mirroring
    'maliit-keyboard',  # maliit generic virtual keyboard
    'sunshine',         # remote server
    'rbw',              # rust bitwarden cli
    'cryptomator-cli',  # encrypted vault/folder
    'zerotier-one',     # virtual LAN
    # ex: timeshift-systemd-timer
]
vlc-plugins = [
    'vlc-plugins-all'   # ALL vlc plugins
]
virt = [
    'qemu-desktop', # QEMU setup for desktop environment
    'virt-manager', # GUI front end for virtualization
    'libvirt',      # virtualization library
    'edk2-ovmf',    # UEFI firmware for virtual machines
    'virt-viewer',  # graphical display required by virt-manager
]
gnome = [
    'gnome-shell-extension-sound-output-device-chooser',
]
print = [
    'cups',                         # The core printing system
    'cups-filters',
    'cups-pdf',                     # Print to PDF support
    'foomatic-db',
    'foomatic-db-engine',
    'foomatic-db-gutenprint-ppds',
    'foomatic-db-nonfree',
    'foomatic-db-nonfree-ppds',
    'foomatic-db-ppds',
    'foomatic-db-gutenprint-ppds',  # PPD files for Gutenprint
    'ghostscript',
    'gsfonts',
    'gutenprint',                   # High-quality drivers for Canon, Epson, etc.
    'hplip',                        # Drivers for HP printers
    'splix',
    'system-config-printer',
]
usbiso = [
    'ventoy',   # ventoy bootloader
    'archiso',  # archiso creation
]
nvidia-580xx = [
    'nvidia-580xx-dkms',
    'nvidia-580xx-utils',
    'nvidia-580xx-settings',
    'lib32-nvidia-580xx-utils',
]