
# partition will be created automatically on an empty space

# partition to find with empty space, if nvme is not empty, then go to sd
partition-order = [
    "/dev/nvme",
    "/dev/sd",
]

[root]
fs = "ext4"
label = "arch-linux-root"
min-size = "100G"

[home]
fs = "ext4"
label = "arch-linux-home"
min-size = "100G"